# Geocoding

In [1]:
import pandas as pd 
import geopandas as gpd 
from shapely.geometry import Point

fp = "data/ch6/Helsinki/addresses.txt"
data = pd.read_csv(fp, sep=";")
data.head()

     id                                           addr
0  1000       Itämerenkatu 14, 00101 Helsinki, Finland
1  1001          Kampinkuja 1, 00100 Helsinki, Finland
2  1002           Kaivokatu 8, 00101 Helsinki, Finland
3  1003  Hermannin rantatie 1, 00580 Helsinki, Finland
4  1005     Tyynenmerenkatu 9, 00220 Helsinki, Finland

In [2]:
from geopandas.tools import geocode

geo = geocode(
    data["addr"], provider="nominatim", 
    user_agent="biscotty", timeout=10
)
geo.head()

,geometry,address
0,POINT (24.91556 60.1632),"Ruoholahti, 14, Itämerenkatu, Ruoholahti, Läns..."
1,POINT (24.93009 60.16846),"1, Kampinkuja, Kamppi, Eteläinen suurpiiri, He..."
2,POINT (24.94153 60.17016),"Espresso House, 8, Kaivokatu, Keskusta, Kluuvi..."
3,POINT (24.97675 60.19438),"Hermannin rantatie, Hermanninranta, Hermanni, ..."
4,POINT (24.92151 60.15662),"9, Tyynenmerenkatu, Jätkäsaari, Länsisatama, E..."

In [3]:
geo.shape

(34, 2)

In [4]:
join = geo.join(data)
join.head()

,geometry,address,id,addr
0,POINT (24.91556 60.1632),"Ruoholahti, 14, Itämerenkatu, Ruoholahti, Läns...",1000,"Itämerenkatu 14, 00101 Helsinki, Finland"
1,POINT (24.93009 60.16846),"1, Kampinkuja, Kamppi, Eteläinen suurpiiri, He...",1001,"Kampinkuja 1, 00100 Helsinki, Finland"
2,POINT (24.94153 60.17016),"Espresso House, 8, Kaivokatu, Keskusta, Kluuvi...",1002,"Kaivokatu 8, 00101 Helsinki, Finland"
3,POINT (24.97675 60.19438),"Hermannin rantatie, Hermanninranta, Hermanni, ...",1003,"Hermannin rantatie 1, 00580 Helsinki, Finland"
4,POINT (24.92151 60.15662),"9, Tyynenmerenkatu, Jätkäsaari, Länsisatama, E...",1005,"Tyynenmerenkatu 9, 00220 Helsinki, Finland"

In [5]:
outfp = "data/addresses.gpkg"
join.to_file(outfp)

In [6]:
address_list = [
    "6119 Mustang Ln NW, Albuquerque, NM 87120",
    "105 S State Street, Ann Arbor, MI 48109",
    "5 Leona Terrace, Mahwah, NJ 07430"
]

geo2 = geocode(
    address_list, provider="nominatim", user_agent="biscotty", timeout=10
)

geo2.head()

,geometry,address
0,POINT (-106.70813 35.14749),"6119, Mustang Lane Northwest, Albuquerque, Ber..."
1,POINT (-83.7399 42.28055),"North Quad Dining Hall, 105, South State Stree..."
2,POINT (-74.15647 41.03768),"5, Leona Terrace, Mahwah, Bergen County, New J..."

In [7]:
geo2.explore(
    color="red", max_zoom=12, marker_kwds=dict(radius=8), 
    tiles="CartoDB Positron"
)

# Reverse geocoding

In [9]:
points = geo[["geometry"]].copy()
points.head()

                    geometry
0   POINT (24.91556 60.1632)
1  POINT (24.93009 60.16846)
2  POINT (24.94153 60.17016)
3  POINT (24.97675 60.19438)
4  POINT (24.92151 60.15662)

In [10]:
points2 = geo2[["geometry"]].copy()
points2.head()

                      geometry
0  POINT (-106.70813 35.14749)
1    POINT (-83.7399 42.28055)
2   POINT (-74.15647 41.03768)

In [12]:
from geopandas.tools import reverse_geocode

reverse_geocoded = reverse_geocode(
    points2.geometry, provider="nominatim", user_agent="biscotty", timeout=10
)
reverse_geocoded.head()

,geometry,address
0,POINT (-106.70813 35.14749),"6119, Mustang Lane Northwest, Albuquerque, Ber..."
1,POINT (-83.7399 42.28055),"North Quad Dining Hall, 105, South State Stree..."
2,POINT (-74.15647 41.03768),"5, Leona Terrace, Mahwah, Bergen County, New J..."